name: live-stt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - python-sounddevice
  - pip:
      - faster-whisper==1.0.3
      - fastapi==0.111.0
      - "uvicorn[standard]==0.30.1"
      - webrtcvad==2.0.10
      - websocket-client==1.8.0
